blog_comment_homepage:
    path: /comment/
    defaults: { _controller: BlogCommentBundle:Comment:index }

blog_comment_new:
    path: /comment/new
    defaults: { _controller: BlogCommentBundle:Comment:new }

blog_comment_create:
    path: /comment/create
    defaults: { _controller: BlogCommentBundle:Comment:create }

blog_comment_show:
    path: /comment/{id}
    defaults: { _controller: BlogCommentBundle:Comment:show }

blog_comment_edit:
    path:     comment/{id}/edit
    defaults: { _controller: BlogCommentBundle:Comment:edit }

blog_comment_update:
    path:     comment/{id}/update
    defaults: { _controller: BlogCommentBundle:Comment:update }

blog_comment_delete:
    path:     comment/{id}/delete
    defaults: { _controller: BlogCommentBundle:Comment:delete }
