blog_post_api_homepage:
    path: api/post/
    defaults: { _controller: BlogPostBundle:Post:indexApi }

blog_post_homepage:
    path: /post/
    defaults: { _controller: BlogPostBundle:Post:index }

blog_post_new:
    path: /post/new
    defaults: { _controller: BlogPostBundle:Post:new }

blog_post_create:
    path: /post/create
    defaults: { _controller: BlogPostBundle:Post:create }

blog_post_show:
    path: /post/{id}
    defaults: { _controller: BlogPostBundle:Post:show }

blog_post_edit:
    path:     post/{id}/edit
    defaults: { _controller: BlogPostBundle:Post:edit }

blog_post_update:
    path:     post/{id}/update
    defaults: { _controller: BlogPostBundle:Post:update }

blog_post_delete:
    path:     post/{id}/delete
    defaults: { _controller: BlogPostBundle:Post:delete }

blog_post_create_comment:
    path: /post/{id}/comment/create
    defaults: { _controller: BlogPostBundle:Post:createComment }
