blog_post_homepage:
    path: /post/
    defaults: { _controller: BlogPostBundle:Post:index }

blog_post_new:
    path: /post/new
    defaults: { _controller: BlogPostBundle:Post:new }

blog_post_create:
    path: /post/create
    defaults: { _controller: BlogPostBundle:Post:create }

blog_post_show:
    path: /post/{id}
    defaults: { _controller: BlogPostBundle:Post:show }